version: '3'

services:
    api:
        build:
            context: ./api
        container_name: project_backend_api
        restart: always
        ports:
            - 5050:5000
        command: 
            --connection postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
            --cors
            --subscriptions
            --retry-on-init-fail
            --watch
            --dynamic-json
            --append-plugins @graphile-contrib/pg-simplify-inflector,@graphile-contrib/pg-order-by-related,postgraphile-plugin-connection-filter
            --no-setof-functions-contain-nulls
            --no-ignore-rbac
            --no-ignore-indexes
            --show-error-stack=json
            --extended-errors hint,detail,errcode
            --export-schema-graphql schema.graphql
            --graphiql "/"
            --enhance-graphiql
            --allow-explain
            --enable-query-batching
            --legacy-relations omit
            --schema app_public

        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_PORT
            - VIRTUAL_HOST=${VIRTUAL_HOST_API}
            - LETSENCRYPT_HOST=${VIRTUAL_HOST_API}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
        depends_on:
            - db
        networks:
            - default
            - proxy

    db:
        image: postgres:alpine
        container_name: project_backend_db
        restart: always
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_PORT
        volumes:
            - db_data:/var/lib/postgresql/data

    admin:
        image: dpage/pgadmin4
        container_name: project_backend_admin
        restart: always
        ports:
            - 5555:80
        environment:
            - PGADMIN_DEFAULT_EMAIL
            - PGADMIN_DEFAULT_PASSWORD
            - VIRTUAL_HOST=${VIRTUAL_HOST_ADMIN}
            - LETSENCRYPT_HOST=${VIRTUAL_HOST_ADMIN}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
        depends_on:
            - db
        volumes:
            - admin_data:/var/lib/pgadmin
        networks:
            - default
            - proxy

volumes:
    db_data:
    admin_data:

networks:
    proxy:
        external: true